[2024-03-24 09:16:55] Started the Error Log File
[2024-03-24 09:18:35] Started the Error Log File
[2024-03-24 09:18:41] Closed the Error Log File




[2024-03-24 09:19:02] Started the Error Log File
[2024-03-24 09:19:03] Closed the Error Log File




[2024-03-24 09:21:24] Started the Error Log File
[2024-03-24 09:32:44] Started the Error Log File
[2024-03-24 09:40:34] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 37, in settings_command
    self.functions['open_settings']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 332, in open_settings
    self.reset_button_press_variable()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SnakeGameApp' object has no attribute 'reset_button_press_variable'
[2024-03-24 09:43:12] Started the Error Log File
[2024-03-24 09:46:21] Started the Error Log File
[2024-03-24 09:46:23] Closed the Error Log File




[2024-03-24 09:47:47] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 37, in settings_command
    self.functions['open_settings']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 333, in open_settings
    self.geeral_reset_button_press_variable()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SnakeGameApp' object has no attribute 'geeral_reset_button_press_variable'
[2024-03-24 09:49:01] Started the Error Log File
[2024-03-24 09:49:26] Started the Error Log File
[2024-03-24 09:49:26] Closed the Error Log File





[2024-03-24 09:55:06] Started the Error Log File
[2024-03-24 09:55:14] Closed the Error Log File




[2024-03-24 09:55:35] Started the Error Log File
[2024-03-24 09:55:37] Closed the Error Log File




[2024-03-24 09:56:05] Started the Error Log File
[2024-03-24 09:56:14] Closed the Error Log File




[2024-03-24 09:57:03] Started the Error Log File
[2024-03-24 09:57:05] No error occurred




[2024-03-24 09:57:05] Closed the Error Log File




[2024-03-24 09:57:17] Started the Error Log File
[2024-03-24 09:57:17] No error occurred
[2024-03-24 09:57:17] Closed the Error Log File




[2024-03-24 10:11:19] Started the Error Log File
[2024-03-24 10:11:31] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 203, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Snake_endless.__init__() missing 1 required positional argument: 'error_logfile'
[2024-03-24 10:28:20] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 200, in snake_endless
    self.classic_eset_button_press_variable()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SnakeGameApp' object has no attribute 'classic_eset_button_press_variable'
[2024-03-24 10:29:36] 


[2024-03-24 10:29:36] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 200, in snake_endless
    self.classic_eset_button_press_variable()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SnakeGameApp' object has no attribute 'classic_eset_button_press_variable'
[2024-03-24 10:30:30] 


[2024-03-24 10:30:30] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 203, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Snake_endless.__init__() missing 1 required positional argument: 'error_logfile'


[2024-03-24 10:30:44] 


[2024-03-24 10:30:44] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 203, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Snake_endless.__init__() missing 1 required positional argument: 'error_logfile'
[2024-03-24 10:31:22] 


[2024-03-24 10:31:22] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 55, in __init__
    self.config.read(self.cofig_path)
                     ^^^^^^^^^^^^^^^
AttributeError: 'Snake_endless' object has no attribute 'cofig_path'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 61, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 229, in snake_endless
    self.game_labels_panel_2 = GameLabelsPanel(self.main_canvas,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 165, in __init__
    self.classic_score_label_ = self.config.set('Classic_Snake_Values', 'score', '0')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Values'
[2024-03-24 10:45:07] 


[2024-03-24 10:45:07] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 26, in __init__
    self.config.set('Classic_Snake_Values','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Values'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 588, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 39, in __init__
    self.theme_updater.set_initial_theme()
  File "e:\Snake_game_V3\Snake_Game_V3\Themes\theme_updater_snake_game.py", line 37, in set_initial_theme
    self.config.add_section('Settings', 'theme') 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigParser.add_section() takes 2 positional arguments but 3 were given
[2024-03-24 10:47:20] 


[2024-03-24 10:47:20] Started the Error Log File
[2024-03-24 10:48:40] 


[2024-03-24 10:48:40] Started the Error Log File
[2024-03-24 10:49:07] 


[2024-03-24 10:49:07] Started the Error Log File
[2024-03-24 10:49:08] No errors occurred
[2024-03-24 10:49:08] Closed the Error Log File




[2024-03-24 10:49:57] 


[2024-03-24 10:49:57] Started the Error Log File
[2024-03-24 10:50:18] No errors occurred
[2024-03-24 10:50:18] Closed the Error Log File




[2024-03-24 13:12:50] 


[2024-03-24 13:12:50] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 569, in endless_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
[2024-03-24 13:15:46] 


[2024-03-24 13:15:46] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
[2024-03-24 13:15:53] 


[2024-03-24 13:15:53] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 569, in endless_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
[2024-03-24 13:22:40] 


[2024-03-24 13:22:40] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 569, in endless_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
[2024-03-24 13:23:11] 


[2024-03-24 13:23:11] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 560, in return_home
    self.endless_snake_canvas.delete_game_labels_()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete_game_labels_'
[2024-03-24 13:23:33] No errors occurred
[2024-03-24 13:23:33] Closed the Error Log File




[2024-03-24 13:24:08] 


[2024-03-24 13:24:08] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'logfile'
[2024-03-24 13:25:45] 


[2024-03-24 13:25:45] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CTkCanvas' object has no attribute 'log_game_event'
[2024-03-24 13:26:42] 


[2024-03-24 13:26:42] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CTkCanvas' object has no attribute 'log_game_event'
[2024-03-24 13:26:44] No errors occurred
[2024-03-24 13:26:44] Closed the Error Log File




[2024-03-24 13:28:34] 


[2024-03-24 13:28:34] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.logfile.log_game_event("delete_labels method called")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CTkCanvas' object has no attribute 'log_game_event'
[2024-03-24 13:28:40] No errors occurred
[2024-03-24 13:28:40] Closed the Error Log File




[2024-03-24 13:29:14] 


[2024-03-24 13:29:14] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    self.classic_score_label.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'classic_score_label'
[2024-03-24 13:29:18] No errors occurred
[2024-03-24 13:29:18] Closed the Error Log File




[2024-03-24 13:31:56] 


[2024-03-24 13:31:56] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 394, in classic_delete_labels
    self.classic_score_label.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'destroy'
[2024-03-24 13:31:57] No errors occurred
[2024-03-24 13:31:57] Closed the Error Log File




[2024-03-24 13:34:00] 


[2024-03-24 13:34:00] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    if self.classic_score_label is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'classic_score_label'
[2024-03-24 13:34:01] No errors occurred
[2024-03-24 13:34:01] Closed the Error Log File




[2024-03-24 13:35:17] 


[2024-03-24 13:35:17] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 377, in classic_delete_labels
    if self.classic_score_label is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'classic_score_label'
[2024-03-24 13:35:18] No errors occurred
[2024-03-24 13:35:18] Closed the Error Log File




[2024-03-24 13:37:56] 


[2024-03-24 13:37:56] Started the Error Log File
[2024-03-24 13:37:57] No errors occurred
[2024-03-24 13:37:57] Closed the Error Log File




[2024-03-24 13:38:04] 


[2024-03-24 13:38:04] Started the Error Log File
[2024-03-24 13:38:07] No errors occurred
[2024-03-24 13:38:07] Closed the Error Log File




[2024-03-24 13:38:22] 


[2024-03-24 13:38:22] Started the Error Log File
[2024-03-24 13:38:23] No errors occurred
[2024-03-24 13:38:23] Closed the Error Log File




[2024-03-24 13:40:00] 


[2024-03-24 13:40:00] Started the Error Log File
[2024-03-24 18:48:44] 


[2024-03-24 18:48:44] Started the Error Log File
[2024-03-24 19:03:21] 


[2024-03-24 19:03:21] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 180, in start_game
    self.food.spawn_food(snake_coordinates, len(snake_coordinates))
TypeError: ClassicFood.spawn_food() takes 2 positional arguments but 3 were given
[2024-03-24 19:04:27] 


[2024-03-24 19:04:27] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 180, in start_game
    self.food.spawn_food(snake_coordinates, len(snake_coordinates))
TypeError: ClassicFood.spawn_food() takes 2 positional arguments but 3 were given
[2024-03-24 19:05:49] 


[2024-03-24 19:05:49] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 213, in next_turn
    food.spawn_food(snake.get_coordinates(), self.score)
TypeError: ClassicFood.spawn_food() takes 2 positional arguments but 3 were given
[2024-03-24 19:06:55] 


[2024-03-24 19:06:55] Started the Error Log File
[2024-03-24 19:07:22] 


[2024-03-24 19:07:22] Started the Error Log File
[2024-03-24 19:07:23] No errors occurred
[2024-03-24 19:07:23] Closed the Error Log File




[2024-03-24 19:09:36] 


[2024-03-24 19:09:36] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 231, in start_game
    self.food.special_spawn_food(snake_coordinates, len(snake_coordinates))
TypeError: EndlessFood.special_spawn_food() takes 2 positional arguments but 3 were given
[2024-03-24 19:10:00] 


[2024-03-24 19:10:00] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 231, in start_game
    self.food.special_spawn_food(snake_coordinates)
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\food_logic_snake_game.py", line 91, in special_spawn_food
    if self.score % 50 == 0:
       ^^^^^^^^^^
AttributeError: 'EndlessFood' object has no attribute 'score'
[2024-03-24 19:10:50] 


[2024-03-24 19:10:50] Started the Error Log File
[2024-03-24 19:11:15] 


[2024-03-24 19:11:15] Started the Error Log File
[2024-03-24 19:11:16] No errors occurred
[2024-03-24 19:11:16] Closed the Error Log File




[2024-03-24 19:14:41] 


[2024-03-24 19:14:41] Started the Error Log File
[2024-03-24 19:19:52] 


[2024-03-24 19:19:52] Started the Error Log File
[2024-03-24 19:35:31] 


[2024-03-24 19:35:31] Started the Error Log File
[2024-03-24 19:39:40] 


[2024-03-24 19:39:40] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 132, in __init__
    if not self.config.has_option('Endless_Snake_Settings', 'next_special_food_score', fallback='50'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RawConfigParser.has_option() got an unexpected keyword argument 'fallback'
[2024-03-24 19:42:20] No errors occurred
[2024-03-24 19:42:20] Closed the Error Log File




[2024-03-24 19:42:23] 


[2024-03-24 19:42:23] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 132, in __init__
    if not self.config.has_section('Endless_Snake_Settings', 'next_special_food_score', fallback='50'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RawConfigParser.has_section() got an unexpected keyword argument 'fallback'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 138, in __init__
    if not self.config.has_option('Endless_Snake_Settings', 'next_special_food_score', fallback='50'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RawConfigParser.has_option() got an unexpected keyword argument 'fallback'
[2024-03-24 19:42:59] 


[2024-03-24 19:42:59] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 132, in __init__
    if not self.config.has_section('Endless_Snake_Settings', 'next_special_food_score', fallback='50'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RawConfigParser.has_section() got an unexpected keyword argument 'fallback'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 138, in __init__
    if not self.config.has_option('Endless_Snake_Settings', 'next_special_food_score', fallback='50'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RawConfigParser.has_option() got an unexpected keyword argument 'fallback'
[2024-03-24 19:43:06] No errors occurred
[2024-03-24 19:43:06] Closed the Error Log File




[2024-03-24 19:45:59] 


[2024-03-24 19:45:59] Started the Error Log File
[2024-03-24 19:46:58] 


[2024-03-24 19:46:58] Started the Error Log File
[2024-03-24 19:55:05] 


[2024-03-24 19:55:05] Started the Error Log File
[2024-03-24 19:57:20] 


[2024-03-24 19:57:20] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 327, in next_turn
    self.food.special_spawn_food(self.snake.get_coordinates(), self.score)
TypeError: EndlessFood.special_spawn_food() takes 2 positional arguments but 3 were given
[2024-03-24 20:00:53] 


[2024-03-24 20:00:53] Started the Error Log File
[2024-03-24 20:01:20] 


[2024-03-24 20:01:20] Started the Error Log File
[2024-03-24 20:03:12] 


[2024-03-24 20:03:12] Started the Error Log File
[2024-03-24 20:06:07] 


[2024-03-24 20:06:07] Started the Error Log File
[2024-03-24 20:07:40] No errors occurred
[2024-03-24 20:07:40] Closed the Error Log File




[2024-03-24 20:07:59] 


[2024-03-24 20:07:59] Started the Error Log File
[2024-03-24 20:11:03] No errors occurred
[2024-03-24 20:11:03] Closed the Error Log File




[2024-03-24 20:11:04] 


[2024-03-24 20:11:04] Started the Error Log File
[2024-03-24 20:11:26] No errors occurred
[2024-03-24 20:11:26] Closed the Error Log File




[2024-03-24 20:11:28] 


[2024-03-24 20:11:28] Started the Error Log File
[2024-03-24 20:14:50] No errors occurred
[2024-03-24 20:14:50] Closed the Error Log File




[2024-03-24 20:14:56] 


[2024-03-24 20:14:56] Started the Error Log File
[2024-03-24 20:17:24] No errors occurred
[2024-03-24 20:17:24] Closed the Error Log File




[2024-03-24 20:17:26] 


[2024-03-24 20:17:26] Started the Error Log File
[2024-03-24 20:17:44] No errors occurred
[2024-03-24 20:17:44] Closed the Error Log File




[2024-03-24 20:17:46] 


[2024-03-24 20:17:46] Started the Error Log File
[2024-03-24 20:18:06] No errors occurred
[2024-03-24 20:18:06] Closed the Error Log File




[2024-03-24 20:19:25] 


[2024-03-24 20:19:25] Started the Error Log File
[2024-03-24 20:19:56] No errors occurred
[2024-03-24 20:19:56] Closed the Error Log File




[2024-03-24 20:19:57] 


[2024-03-24 20:19:57] Started the Error Log File
[2024-03-24 20:20:06] No errors occurred
[2024-03-24 20:20:06] Closed the Error Log File




[2024-03-24 20:20:08] 


[2024-03-24 20:20:08] Started the Error Log File
[2024-03-24 20:20:57] 


[2024-03-24 20:20:57] Started the Error Log File
[2024-03-24 20:23:56] No errors occurred
[2024-03-24 20:23:56] Closed the Error Log File




[2024-03-24 20:24:04] 


[2024-03-24 20:24:04] Started the Error Log File
[2024-03-24 20:24:48] No errors occurred
[2024-03-24 20:24:48] Closed the Error Log File




[2024-03-24 20:28:37] 


[2024-03-24 20:28:37] Started the Error Log File
[2024-03-24 20:32:28] 


[2024-03-24 20:32:28] Started the Error Log File
[2024-03-24 20:34:22] No errors occurred
[2024-03-24 20:34:22] Closed the Error Log File




[2024-03-24 20:34:25] 


[2024-03-24 20:34:25] Started the Error Log File
[2024-03-24 20:37:26] No errors occurred
[2024-03-24 20:37:26] Closed the Error Log File




[2024-03-24 20:37:27] 


[2024-03-24 20:37:27] Started the Error Log File
[2024-03-24 20:38:02] No errors occurred
[2024-03-24 20:38:02] Closed the Error Log File




[2024-03-24 20:47:50] 


[2024-03-24 20:47:50] Started the Error Log File
[2024-03-24 20:51:28] 


[2024-03-24 20:51:28] Started the Error Log File
[2024-03-24 20:52:02] No errors occurred
[2024-03-24 20:52:02] Closed the Error Log File




[2024-03-24 20:58:03] 


[2024-03-24 20:58:03] Started the Error Log File
[2024-03-24 20:58:08] No errors occurred
[2024-03-24 20:58:08] Closed the Error Log File




[2024-03-24 21:00:56] 


[2024-03-24 21:00:56] Started the Error Log File
[2024-03-24 21:06:51] 


[2024-03-24 21:06:51] Started the Error Log File
[2024-03-24 21:07:12] No errors occurred
[2024-03-24 21:07:12] Closed the Error Log File




[2024-03-24 21:07:15] 


[2024-03-24 21:07:15] Started the Error Log File
[2024-03-24 21:07:41] No errors occurred
[2024-03-24 21:07:41] Closed the Error Log File




[2024-03-25 19:22:24] 


[2024-03-25 19:22:24] Started the Error Log File
[2024-03-25 19:25:19] 


[2024-03-25 19:25:19] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 614, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 39, in __init__
    self.theme_updater.set_initial_theme()
  File "e:\Snake_game_V3\Snake_Game_V3\Themes\theme_updater_snake_game.py", line 37, in set_initial_theme
    self.config.set('Settings', 'theme') 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1219, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1204, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
[2024-03-25 19:27:38] 


[2024-03-25 19:27:38] Started the Error Log File
[2024-03-25 19:28:17] 


[2024-03-25 19:28:17] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 202, in __init__
    self.classic_score_label_ = self.config.set('Classic_Snake_Values', 'score', '0')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Values'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 202, in __init__
    self.classic_score_label_ = self.config.set('Classic_Snake_Values', 'score', '0')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Values'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 54, in classic_snake_command
    self.functions['classic_snake']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 156, in classic_snake
    self.classic_snake_canvas = Snake_Classic_Game(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 53, in __init__
    self.game_labels_panel.classic_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 215, in classic_create_game_labels
    self.classic_create_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 238, in classic_create_score_label
    text=f"Score:{self.classic_score_label_} Food eaten",
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'classic_score_label_'
[2024-03-25 19:59:56] 


[2024-03-25 19:59:56] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 202, in __init__
    self.classic_score_label_ = self.config.set('Classic_Snake_Values', 'score', '0')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Values'
[2024-03-25 20:00:45] No errors occurred
[2024-03-25 20:00:45] Closed the Error Log File




[2024-03-25 20:00:49] 


[2024-03-25 20:00:49] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 205, in __init__
    self.endless_score_label_ = self.config.set('Endless_Snake_Values', 'score', '0')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Endless_Snake_Values'
[2024-03-25 20:01:53] No errors occurred
[2024-03-25 20:01:53] Closed the Error Log File




[2024-03-25 20:01:55] 


[2024-03-25 20:01:55] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 616, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 36, in __init__
    self.config_ini = ConfigIni()
                      ^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\config_ini_Initials.py", line 14, in __init__
    self.set_classic_snake_settings()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\config_ini_Initials.py", line 60, in set_classic_snake_settings
    self.config.set('Classic_Snake_Settings', 'state', 'start_game')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Settings'
[2024-03-25 20:05:37] 


[2024-03-25 20:05:37] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 617, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 36, in __init__
    self.config_ini = ConfigIni()
                      ^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\config_ini_Initials.py", line 14, in __init__
    self.set_classic_snake_settings()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\config_ini_Initials.py", line 60, in set_classic_snake_settings
    self.config.set('Classic_Snake_Settings', 'state', 'start_game')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Classic_Snake_Settings'
[2024-03-25 20:06:44] 


[2024-03-25 20:06:44] Started the Error Log File
[2024-03-25 20:08:26] 


[2024-03-25 20:08:26] Started the Error Log File
[2024-03-25 20:14:43] 


[2024-03-25 20:14:43] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 617, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 54, in __init__
    self.update_contrast.apply_contrast(selected_value=None)
  File "e:\Snake_game_V3\Snake_Game_V3\Themes\contrast_updater_snake_game.py", line 23, in apply_contrast
    self.update_config_contrast(selected_value)
  File "e:\Snake_game_V3\Snake_Game_V3\Themes\contrast_updater_snake_game.py", line 39, in update_config_contrast
    self.config.set('Settings', 'contrast', selected_value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-25 20:15:00] 


[2024-03-25 20:15:00] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Green')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-25 20:49:06] 


[2024-03-25 20:49:06] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 20, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-25 20:49:08] No errors occurred
[2024-03-25 20:49:08] Closed the Error Log File




[2024-03-25 20:56:14] 


[2024-03-25 20:56:14] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 667, in endless_update_shorten_food_score_label
    self.endless_shorten_food_score.configure(text=f"Shorten Food Score: {self.endless_shorten_food_score_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 691, in endless_update_shorten_food_high_score_label
    self.endless_shorten_food_high_score.configure(text=f"Shorten Food Score: {self.endless_shorten_food_high_score_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-25 20:58:11] 


[2024-03-25 20:58:11] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_food_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_food_score_label
    text=f"Shorten Food Score:{self.endless_shorten_food_score_} Food eaten",
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score_'
[2024-03-25 21:02:52] 


[2024-03-25 21:02:52] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_food_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_food_score_label
    text=f"Shorten Food Score:{self.endless_shorten_food_score_} Food eaten",
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score_'
[2024-03-25 21:08:35] 


[2024-03-25 21:08:35] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:09:40] 


[2024-03-25 21:09:40] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:13:05] 


[2024-03-25 21:13:05] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:18:20] 


[2024-03-25 21:18:20] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:18:32] 


[2024-03-25 21:18:32] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 207, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:19:27] 


[2024-03-25 21:19:27] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 19, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 208, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:21:50] 


[2024-03-25 21:21:50] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 22, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 22, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 208, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-25 21:23:49] 


[2024-03-25 21:23:49] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 654, in endless_create_shorten_score_label
    text=f"Shorten Score:{self.endless_shorten_score_} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_score_'
[2024-03-27 17:09:58] 


[2024-03-27 17:09:58] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 693, in endless_update_shorten_high_score_label
    self.endless_shorten_high_score.configure(text=f"Shorten Score: {self.endless_shorten_high_score_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 148, in __init__
    self.start_screen()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 177, in start_screen
    self.game_labels_panel_2.endless_update_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 442, in endless_update_game_labels
    self.endless_update_shorten_food_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_update_shorten_food_score_label'
[2024-03-27 17:11:52] 


[2024-03-27 17:11:52] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 693, in endless_update_shorten_high_score_label
    self.endless_shorten_food_score_label.configure(text=f"Shorten Score: {self.endless_shorten_high_score_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'configure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 148, in __init__
    self.start_screen()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 177, in start_screen
    self.game_labels_panel_2.endless_update_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 442, in endless_update_game_labels
    self.endless_update_shorten_food_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_update_shorten_food_score_label'
[2024-03-27 17:13:06] 


[2024-03-27 17:13:06] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 427, in endless_create_game_labels
    self.endless_create_shorten_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_create_shorten_score_label'
[2024-03-27 17:14:36] 


[2024-03-27 17:14:36] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 148, in __init__
    self.start_screen()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 177, in start_screen
    self.game_labels_panel_2.endless_update_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 442, in endless_update_game_labels
    self.endless_update_shorten_food_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_update_shorten_food_score_label'
[2024-03-27 17:15:35] 


[2024-03-27 17:15:35] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 148, in __init__
    self.start_screen()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 177, in start_screen
    self.game_labels_panel_2.endless_update_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 442, in endless_update_game_labels
    self.endless_update_shorten_food_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_update_shorten_food_score_label'
[2024-03-27 17:17:47] 


[2024-03-27 17:17:47] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 148, in __init__
    self.start_screen()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 177, in start_screen
    self.game_labels_panel_2.endless_update_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 442, in endless_update_game_labels
    self.endless_update_shorten_food_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_update_shorten_food_score_label'
[2024-03-27 17:20:58] 


[2024-03-27 17:20:58] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-27 17:25:16] No errors occurred
[2024-03-27 17:25:16] Closed the Error Log File




[2024-03-27 17:25:21] 


[2024-03-27 17:25:21] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 425, in endless_create_game_labels
    self.endless_create_special_score_label()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_create_special_score_label'
[2024-03-27 17:28:14] 


[2024-03-27 17:28:14] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-27 17:29:21] No errors occurred
[2024-03-27 17:29:21] Closed the Error Log File




[2024-03-27 17:29:26] 


[2024-03-27 17:29:26] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-27 18:20:00] 


[2024-03-27 18:20:00] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 60, in snake_endless_command
    self.functions['snake_endless']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 209, in snake_endless
    self.endless_snake_canvas = Snake_endless(self.root,
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 51, in __init__
    self.game_labels_panel_2.endless_create_game_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 425, in endless_create_game_labels
    self.endless_create_special_score_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 605, in endless_create_special_score_label
    text=f"Special Score:{self.endless_special_score_label} Food eaten",
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_special_score_label'
[2024-03-27 18:21:51] 


[2024-03-27 18:21:51] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Configuration\gameconfig_snake_game.py", line 23, in __init__
    self.config.set('Settings','snake_color', 'Default')
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1220, in set
    super().set(section, option, value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 918, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
[2024-03-27 18:23:54] No errors occurred
[2024-03-27 18:23:54] Closed the Error Log File




[2024-03-27 18:26:21] 


[2024-03-27 18:26:21] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 683, in endless_delete_labels
    if self.endless_shorten_food_score is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score'
[2024-03-27 18:26:30] No errors occurred
[2024-03-27 18:26:30] Closed the Error Log File




[2024-03-27 18:31:10] 


[2024-03-27 18:31:10] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 620, in endless_update_special_score_label
    self.endless_special_score.configure(text=f"Special Score: {self.endless_special_score_label_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_special_score'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 644, in endless_update_special_high_score_label
    self.endless_special_high_score_label.configure(text=f"Special Score: {self.endless_special_high_score_label} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'configure'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 682, in endless_delete_labels
    self.endless_special_high_score_label.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'destroy'
[2024-03-27 18:32:21] 


[2024-03-27 18:32:21] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 620, in endless_update_special_score_label
    self.endless_special_score.configure(text=f"Special Score: {self.endless_special_score_label_} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_special_score'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 644, in endless_update_special_high_score_label
    self.endless_special_high_score_label.configure(text=f"Special Score: {self.endless_special_high_score_label} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'configure'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 682, in endless_delete_labels
    self.endless_special_high_score_label.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'destroy'
[2024-03-27 18:32:25] No errors occurred
[2024-03-27 18:32:25] Closed the Error Log File




[2024-03-27 18:33:43] 


[2024-03-27 18:33:43] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 644, in endless_update_special_high_score_label
    self.endless_special_high_score_label.configure(text=f"Special Score: {self.endless_special_high_score_label} Food eaten")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'configure'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 682, in endless_delete_labels
    self.endless_special_high_score_label.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'destroy'
[2024-03-27 18:35:51] 


[2024-03-27 18:35:51] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 683, in endless_delete_labels
    if self.endless_shorten_food_score is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score'
[2024-03-27 18:36:00] No errors occurred
[2024-03-27 18:36:00] Closed the Error Log File




[2024-03-27 18:39:17] 


[2024-03-27 18:39:17] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 720, in endless_delete_labels
    if self.endless_shorten_food_score is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 720, in endless_delete_labels
    if self.endless_shorten_food_score is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score'
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 720, in endless_delete_labels
    if self.endless_shorten_food_score is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_shorten_food_score'
[2024-03-27 18:39:36] No errors occurred
[2024-03-27 18:39:36] Closed the Error Log File




[2024-03-27 18:41:05] 


[2024-03-27 18:41:05] Started the Error Log File
[2024-03-27 18:41:12] No errors occurred
[2024-03-27 18:41:12] Closed the Error Log File




[2024-03-27 18:43:01] 


[2024-03-27 18:43:01] Started the Error Log File
[2024-03-27 18:43:07] No errors occurred
[2024-03-27 18:43:07] Closed the Error Log File




[2024-03-27 18:43:52] 


[2024-03-27 18:43:52] Started the Error Log File
[2024-03-27 18:43:56] No errors occurred
[2024-03-27 18:43:56] Closed the Error Log File




[2024-03-27 18:45:51] 


[2024-03-27 18:45:51] Started the Error Log File
[2024-03-27 18:47:15] No errors occurred
[2024-03-27 18:47:15] Closed the Error Log File




[2024-03-27 18:47:19] 


[2024-03-27 18:47:19] Started the Error Log File
[2024-03-27 18:49:43] No errors occurred
[2024-03-27 18:49:43] Closed the Error Log File




[2024-03-27 18:49:48] 


[2024-03-27 18:49:48] Started the Error Log File
[2024-03-27 18:51:53] No errors occurred
[2024-03-27 18:51:53] Closed the Error Log File




[2024-03-27 18:51:57] 


[2024-03-27 18:51:57] Started the Error Log File
[2024-03-27 18:52:07] No errors occurred
[2024-03-27 18:52:07] Closed the Error Log File




[2024-03-27 18:52:46] 


[2024-03-27 18:52:46] Started the Error Log File
[2024-03-27 18:53:33] 


[2024-03-27 18:53:33] Started the Error Log File
[2024-03-27 19:15:00] No errors occurred
[2024-03-27 19:15:00] Closed the Error Log File




[2024-03-27 19:27:42] 


[2024-03-27 19:27:42] Started the Error Log File
[2024-03-27 19:30:28] No errors occurred
[2024-03-27 19:30:28] Closed the Error Log File




[2024-03-27 19:30:31] 


[2024-03-27 19:30:31] Started the Error Log File
[2024-03-27 19:30:53] No errors occurred
[2024-03-27 19:30:53] Closed the Error Log File




[2024-03-27 19:35:01] 


[2024-03-27 19:35:01] Started the Error Log File
[2024-03-27 19:35:24] No errors occurred
[2024-03-27 19:35:24] Closed the Error Log File




[2024-03-27 19:35:26] 


[2024-03-27 19:35:26] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 114, in endless_reset_high_score_time_command
    self.functions['endless_reset_high_score_time']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 501, in endless_reset_high_score_time
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 120, in endless_reset_high_score_snake_length_command
    self.functions['endless_reset_high_score_snake_length']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 525, in endless_reset_high_score_snake_length
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 120, in endless_reset_high_score_snake_length_command
    self.functions['endless_reset_high_score_snake_length']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 525, in endless_reset_high_score_snake_length
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 126, in endless_reset_high_special_score_command
    self.functions['endless_reset_high_score_special_score']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 549, in endless_reset_high_score_special_score
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 126, in endless_reset_high_special_score_command
    self.functions['endless_reset_high_score_special_score']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 549, in endless_reset_high_score_special_score
    elif self.endless_button_press_variable_high_score_time == 1 and time.time() - self.first_button_press_time <= self.button_press_time_limit:
                                                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
[2024-03-27 19:37:08] No errors occurred
[2024-03-27 19:37:08] Closed the Error Log File




[2024-03-27 19:41:34] 


[2024-03-27 19:41:34] Started the Error Log File
[2024-03-27 19:43:44] No errors occurred
[2024-03-27 19:43:44] Closed the Error Log File




[2024-03-27 19:43:46] 


[2024-03-27 19:43:46] Started the Error Log File
[2024-03-27 19:45:55] No errors occurred
[2024-03-27 19:45:55] Closed the Error Log File




[2024-03-27 19:45:57] 


[2024-03-27 19:45:57] Started the Error Log File
[2024-03-27 19:47:56] No errors occurred
[2024-03-27 19:47:56] Closed the Error Log File




[2024-03-27 19:48:04] 


[2024-03-27 19:48:04] Started the Error Log File
[2024-03-27 19:48:42] No errors occurred
[2024-03-27 19:48:42] Closed the Error Log File




[2024-03-27 19:48:48] 


[2024-03-27 19:48:48] Started the Error Log File
[2024-03-27 19:52:20] 


[2024-03-27 19:52:20] Started the Error Log File
[2024-03-27 19:53:10] No errors occurred
[2024-03-27 19:53:10] Closed the Error Log File




[2024-03-27 20:13:35] 


[2024-03-27 20:13:35] Started the Error Log File
[2024-03-27 20:17:19] 


[2024-03-27 20:17:19] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 354, in next_turn
    if len(food.shorten_food_coordinates) < 1:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EndlessFood' object has no attribute 'shorten_food_coordinates'
[2024-03-27 20:18:08] No errors occurred
[2024-03-27 20:18:08] Closed the Error Log File




[2024-03-27 20:21:02] 


[2024-03-27 20:21:02] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_endless_game.py", line 354, in next_turn
    if len(food.shorten_food_coordinates) < 1:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EndlessFood' object has no attribute 'shorten_food_coordinates'
[2024-03-27 20:21:23] No errors occurred
[2024-03-27 20:21:23] Closed the Error Log File




[2024-03-27 20:22:15] 


[2024-03-27 20:22:15] Started the Error Log File
[2024-03-27 20:23:05] No errors occurred
[2024-03-27 20:23:05] Closed the Error Log File




[2024-03-27 20:24:18] 


[2024-03-27 20:24:18] Started the Error Log File
[2024-03-27 20:25:08] No errors occurred
[2024-03-27 20:25:08] Closed the Error Log File




[2024-03-27 20:30:05] 


[2024-03-27 20:30:05] Started the Error Log File
[2024-03-27 20:30:29] No errors occurred
[2024-03-27 20:30:29] Closed the Error Log File




[2024-03-27 20:34:36] 


[2024-03-27 20:34:36] Started the Error Log File
[2024-03-27 20:36:11] No errors occurred
[2024-03-27 20:36:11] Closed the Error Log File




[2024-03-27 20:36:53] 


[2024-03-27 20:36:53] Started the Error Log File
[2024-03-27 20:37:47] No errors occurred
[2024-03-27 20:37:47] Closed the Error Log File




[2024-03-27 20:39:34] 


[2024-03-27 20:39:34] Started the Error Log File
[2024-03-27 20:40:14] No errors occurred
[2024-03-27 20:40:14] Closed the Error Log File




[2024-03-27 20:41:25] 


[2024-03-27 20:41:25] Started the Error Log File
[2024-03-27 20:42:21] No errors occurred
[2024-03-27 20:42:21] Closed the Error Log File




[2024-03-27 20:44:00] 


[2024-03-27 20:44:00] Started the Error Log File
[2024-03-27 20:44:01] No errors occurred
[2024-03-27 20:44:01] Closed the Error Log File




[2024-03-27 20:47:16] 


[2024-03-27 20:47:16] Started the Error Log File
[2024-03-27 20:47:52] No errors occurred
[2024-03-27 20:47:52] Closed the Error Log File




[2024-03-27 20:50:21] 


[2024-03-27 20:50:21] Started the Error Log File
[2024-03-27 20:55:27] 


[2024-03-27 20:55:27] Started the Error Log File
[2024-03-27 20:59:50] No errors occurred
[2024-03-27 20:59:50] Closed the Error Log File




[2024-03-27 20:59:52] 


[2024-03-27 20:59:52] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 477, in endless_update_score_label
    self.endless_score_label.configure(text=f"Score: {self.endless_high_score_label_} ")
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GameLabelsPanel' object has no attribute 'endless_high_score_label_'
[2024-03-27 21:00:16] No errors occurred
[2024-03-27 21:00:16] Closed the Error Log File




[2024-03-27 21:01:01] 


[2024-03-27 21:01:01] Started the Error Log File
[2024-03-27 21:03:54] 


[2024-03-27 21:03:54] Started the Error Log File
[2024-03-27 21:12:05] 


[2024-03-27 21:12:05] Started the Error Log File
[2024-03-27 21:12:35] 


[2024-03-27 21:12:35] Started the Error Log File
